Repository COSC481W-2023Fall/Bookworm, pull requests merged in 2023-10, with the labels that each got.

#5 Setup repository
  .gitignore
  README.md
  backend/README.md
  backend/package-lock.json
  backend/package.json
  backend/src/index.ts
  backend/tsconfig.json
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/README.md
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: type: feature

#7 Move tests into their own folder
  backend/package.json
  backend/src/sum.ts
  backend/tests/sum.test.ts
  backend/tsconfig.build.json
  frontend/src/sum.ts
  frontend/tests/sum.test.ts
  frontend/tsconfig.json
Labels: scope: ci/cd

#8 Introduce automatic testing on pull requests
  .github/workflows/pr.yml
Labels: scope: ci/cd, Sprint 1

#11 Add the home page
  .prettierrc
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/Bookshelf.module.css
  frontend/src/components/Bookshelf.tsx
  frontend/src/components/Navbar.module.css
  frontend/src/components/Navbar.tsx
  frontend/src/global.module.css
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/Browse.tsx
  frontend/src/pages/Home.module.css
  frontend/src/pages/Home.tsx
  frontend/src/pages/SignIn.tsx
  frontend/src/pages/SignUp.tsx
Labels: type: feature, scope: ui/ux, Sprint 1

#13 Run prettier and ESLint on every PR
  .github/workflows/pr.yml
  .prettierignore
  frontend/src/sum.ts
  frontend/tests/sum.test.ts
  package-lock.json
  package.json
Labels: type: enhancement, scope: ci/cd, Sprint 1

#14 Update babel to address CVE
  frontend/package-lock.json
Labels: type: bug, scope: ui/ux, Sprint 1

#10 Add book browsing page
  .github/workflows/pr.yml
  backend/src/index.ts
  backend/src/models/book.ts
  backend/src/models/index.ts
  backend/src/sum.ts
  backend/tests/sum.test.ts
  backend/tests/unit/book.test.ts
  frontend/.eslintrc.cjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/BrowsePage.tsx
  frontend/src/main.tsx
  frontend/src/pages/Browse.tsx
  frontend/src/services/index.ts
Labels: type: feature, scope: ui/ux, scope: backend, Sprint 1

#22 feat: Add user authentication
  backend/README.md
  backend/package-lock.json
  backend/package.json
  backend/src/index.ts
  backend/src/models/user.ts
  frontend/package-lock.json
  frontend/src/components/Navbar.tsx
  frontend/src/pages/Browse.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/SignIn.module.css
  frontend/src/pages/SignIn.tsx
  frontend/src/pages/SignInForm.tsx
  frontend/src/pages/SignUp.tsx
  frontend/src/pages/SigninC.css
  frontend/src/pages/UserAuth.tsx
  frontend/src/pages/signup-styles.css
  frontend/src/pages/signupApp.tsx
  frontend/src/services/index.ts
  frontend/src/styles.css
Labels: scope: ui/ux, Sprint 1

#30 Fix Deploy Errors, Add Build CI Job
  .github/workflows/pr.yml
  backend/src/index.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/SignUp.tsx
  frontend/src/services/index.ts
Labels: type: bug, scope: ui/ux, scope: ci/cd, Sprint 2

#35 Database logic cleanup
  backend/README.md
  backend/src/index.ts
  backend/src/models/book.ts
  frontend/src/services/index.ts
Labels: type: enhancement, scope: backend, status: BLOCKED, Sprint 2

#38 fix: missed db field name correction
  frontend/src/components/BrowsePage.tsx
Labels: type: bug, scope: ui/ux, Sprint 2
