Repository COSC481W-2023Fall/Bookworm, pull requests merged in 2023-11, with the labels that each got.

#44 Search Books
  backend/src/index.ts
  backend/src/models/book.ts
  backend/tests/unit/book.test.ts
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/Bookshelf.module.css
  frontend/src/components/Bookshelf.tsx
  frontend/src/components/Navbar.module.css
  frontend/src/components/Navbar.tsx
  frontend/src/components/SearchDisplay.tsx
  frontend/src/pages/Search.tsx
  frontend/src/services/index.ts
Labels: type: feature, status: in progress, scope: ui/ux, scope: backend, Sprint 2

#45 Shwetha/Rey - Bookview
  backend/src/models/book.ts
  frontend/public/image_not_available.png
  frontend/src/App.tsx
  frontend/src/pages/BookView.module.css
  frontend/src/pages/BookView.tsx
  frontend/src/services/index.ts
Labels: type: feature, scope: ui/ux, Sprint 2

#47 Update axios to address security vulnerability
  frontend/package-lock.json
  frontend/package.json
Labels: type: bug, scope: ui/ux, Sprint 2

#48 Tasha create bookshelf
  backend/package-lock.json
  backend/src/databaseConnection.ts
  backend/src/index.ts
  backend/src/middleware.ts
  backend/src/models/book.ts
  backend/src/models/index.ts
  backend/src/models/user.ts
  backend/tests/unit/book.test.ts
  backend/tests/unit/user.test.ts
  frontend/src/App.tsx
  frontend/src/components/ShelfPage.tsx
  frontend/src/pages/BookView.module.css
  frontend/src/pages/BookView.tsx
  frontend/src/pages/Shelf.tsx
  frontend/src/services/index.ts
Labels: type: feature, scope: ui/ux, scope: ci/cd, Sprint 2

#43 Book Reviews
  backend/package-lock.json
  backend/package.json
  backend/src/index.ts
  backend/src/middleware.ts
  backend/src/models/book.ts
  frontend/src/App.tsx
  frontend/src/components/ReviewBox.module.css
  frontend/src/components/ReviewBox.tsx
  frontend/src/components/SearchDisplay.tsx
  frontend/src/pages/BookView.module.css
  frontend/src/pages/BookView.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Reviews.module.css
  frontend/src/pages/Reviews.tsx
  frontend/src/pages/SignIn.tsx
  frontend/src/services/index.ts
Labels: type: feature, scope: ui/ux, scope: backend, Sprint 2

#46 Add user profiles
  backend/src/index.ts
  backend/src/middleware.ts
  backend/src/models/editProfile.ts
  backend/src/models/user.ts
  backend/tests/unit/user.test.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Avatar.tsx
  frontend/src/components/Bookshelf.module.css
  frontend/src/components/Navbar.tsx
  frontend/src/components/ShowUserAvatar.tsx
  frontend/src/pages/BookView.tsx
  frontend/src/pages/EditProfile.css
  frontend/src/pages/EditProfile.tsx
  frontend/src/pages/Profile.css
  frontend/src/pages/Profile.tsx
  frontend/src/pages/ProfileLayout.tsx
  frontend/src/pages/Reviews.tsx
  frontend/src/pages/SetPassword.tsx
  frontend/src/pages/ShowProfile.tsx
  frontend/src/pages/ShowProfileLayout.tsx
  frontend/src/pages/SignInForm.tsx
  frontend/src/pages/SignUp.tsx
  frontend/src/pages/signup-styles.css
  frontend/src/services/index.ts
  package-lock.json
  package.json
Labels: type: feature, scope: ui/ux, scope: backend, Sprint 2

#51 Fix inability to save profile data, bookshelves
  backend/src/index.ts
  backend/src/models/editProfile.ts
  backend/src/models/profile.ts
  frontend/src/components/ShelfPage.tsx
  frontend/src/services/index.ts
Labels: type: bug, scope: backend, Beta Testing

#63 Resolving No Access to Profile Page Without Sign-in and Preventing Redirect to Other Page on Refresh
  frontend/src/pages/EditProfile.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/pages/ProfileLayout.tsx
  frontend/src/pages/SetPassword.tsx
  frontend/src/pages/Shelf.tsx
  frontend/src/pages/ShowProfile.tsx
  frontend/src/pages/SignUp.tsx
  package-lock.json
  package.json
Labels: scope: ui/ux, Beta Testing

#62 Improve consistency between sign-up and sign-in pages
  frontend/src/pages/EditProfile.css
  frontend/src/pages/EditProfile.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/pages/SetPassword.tsx
  frontend/src/pages/SignUp.tsx
  frontend/src/pages/signup-styles.css
Labels: type: enhancement, scope: ui/ux, Beta Testing

#61 Change review box icons to use review author icons
  frontend/src/components/ReviewBox.tsx
  frontend/src/components/ShowUserAvatar.tsx
Labels: type: enhancement, scope: ui/ux, Beta Testing

#68 Revert "Change review box icons to use review author icons"
  frontend/src/components/ReviewBox.tsx
  frontend/src/components/ShowUserAvatar.tsx
Labels: type: bug, scope: ui/ux, Beta Testing
