Repository COSC481W-2023Fall/Bookworm, pull requests merged in 2023-12, with the labels that each got.

#72 Re-introduce consistency improvements in signup, sign-in, and edit profile pages
  frontend/src/pages/EditProfile.css
  frontend/src/pages/EditProfile.tsx
  frontend/src/pages/ErrorPage.css
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/pages/SetPassword.tsx
  frontend/src/pages/ShowProfile.tsx
  frontend/src/pages/ShowProfileLayout.tsx
  frontend/src/pages/SignUp.tsx
  frontend/src/pages/signup-styles.css
Labels: type: enhancement, scope: ui/ux, Beta Testing

#71 Re-introduce review icons
  frontend/src/components/ReviewBox.tsx
  frontend/src/components/ShowUserAvatar.tsx
Labels: type: enhancement, scope: ui/ux, Beta Testing

#77 fix: change logo path to work on production
  frontend/src/components/Navbar.tsx
Labels: scope: ui/ux, Beta Testing

#67 Add "Sort By" functionality to the search page
  backend/src/index.ts
  backend/src/models/book.ts
  backend/tests/unit/book.test.ts
  frontend/src/components/Navbar.tsx
  frontend/src/components/SearchDisplay.tsx
  frontend/src/pages/Search.tsx
  frontend/src/services/index.ts
Labels: type: feature, scope: ui/ux, scope: backend, Beta Testing

#73 feat: Add feedback modals to review functionality
  frontend/src/components/ReviewBox.tsx
Labels: type: enhancement, scope: ui/ux, Beta Testing

#74 Improve Navbar
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Navbar.css
  frontend/src/components/Navbar.tsx
  frontend/src/components/dropDown.tsx
Labels: type: feature, scope: ui/ux, Beta Testing

#78 fix: Broken fallback images for book covers
  frontend/src/components/SearchDisplay.tsx
  frontend/src/pages/BookView.tsx
Labels: type: bug, scope: ui/ux, Beta Testing
